# Generated by Django 3.0.2 on 2020-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('Free', 'Free'), ('One-Month', 'One Month'), ('Six-Months', 'Six Months')], max_length=10)),
                ('price', models.IntegerField(default=0)),
                ('ad_posting_limit', models.IntegerField(default=0)),
            ],
        ),
    ]
