# Generated by Django 3.0.2 on 2020-03-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='pack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.package'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='sub_status',
            field=models.CharField(choices=[('N', 'None'), ('S', 'Subscribed'), ('E', 'Expired')], default='N', max_length=1),
        ),
    ]
