# Generated by Django 3.0.2 on 2020-03-17 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('S', 'Sale'), ('R', 'Rent')], max_length=1)),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('HO', 'House'), ('PL', 'Plot')], max_length=2)),
                ('area', models.FloatField()),
                ('beds', models.PositiveIntegerField(null=True)),
                ('baths', models.PositiveIntegerField(null=True)),
                ('garage', models.PositiveIntegerField(null=True)),
                ('price', models.FloatField()),
                ('property_desc', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='property_pics')),
                ('pst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realestate.post')),
            ],
        ),
    ]
