# Generated by Django 3.0.2 on 2020-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=4),
        ),
    ]
