# Generated by Django 3.0.2 on 2020-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0004_auto_20200411_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='baths',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='beds',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='garage',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
